### PR TITLE
eterministically -> deterministically

### PR DESCRIPTION
**Pull request by mikejsavage**
Small docs typo :d

### CODE REVIEW

**Comment by LoupVaillant** [comment]
Merged, thanks!

**Comment by mikejsavage** [comment]
BTW do you need help with anything in the documentation?

I don't know the domain well enough to offer code but I am a native English speaker so I can proof read etc anything you think is dodgy.

**Comment by CuleX** [comment]
The more eyes on the manuals, the better. It looks like the next release should also be the final one. It would be pretty terrible to have a new release for a few deficiencies in the manual.

Check the recent commits, go over the manuals that @LoupVaillant has already reviewed with the finest comb you can find and PR changes. When the next manual review rolls around, join the round and point out things that were missed or degressions by the new changes.

**Comment by LoupVaillant** [comment]
That's… exactly the plan.

The Commits we're talking about are all called "Manual review <something>". The earliest one dates back mid-october.

I favour short sentences. @CuleX convinced me to keep a formal style which means avoiding contractions, and not addressing the user directly ("you") if it's not too awkward. Clarity comes first, though. I'm willing to sacrifice style if it gets the message across more efficiently.

The fact you @mikejsavage aren't a domain expert is actually an asset. If you fail to understand something, the manual may need clarifying. I'm especially scared of ambiguities that could lead to misuse (stuff like nonce reuse, improper random number generation, or failure to wipe secrets). If you spot such a loophole, I want to know.

I have yet to review the manuals of `crypto_lock`, `crypto_lock_init`, `crypto_sign`, `crypto_sign_init`, and the introduction.  I hope to be done before the end of the week.

And welcome!

**Comment by CuleX** [comment]
@mikejsavage it seems that @LoupVaillant is thinking of releasing soon. If you want to get some time to go over the entire manual again, you should probably speak up now with some estimate of how long it'll take you.

**Comment by mikejsavage** [comment]
I was going to start on that today

The manual isn't super big so hopefully it won't take more than a few days.

**Comment by CuleX** [comment]
CC @LoupVaillant ^

**Comment by LoupVaillant** [comment]
Excellent, thank you! Indeed, I've done everything I can. The only way to make the manual better now is external feedback. Yours is most welcome.

**Pull request merged**
