### PR TITLE
Revamp man pages for recent changes

### PR DESCRIPTION
**Pull request by CuleX**
New functions documented:
* crypto_sign (incremental interface)
* crypto_verify16/32/64

Deprecated functions:
* crypto_memcmp
* crypto_zerocmp

Other changes:
* crypto_lock and crypto_aead_lock pages have been merged as they are
  closer to each other in complexity than the incremental and low-level
  crypto_lock interface.

The crypto_memcmp and crypto_zerocmp pages have not been removed in case
people still have references to those functions in their code and are
wondering what the canonical replacement is.

### CODE REVIEW

**Comment by LoupVaillant** [comment]
That's wonderful, thank you! I was dragging my feet to get this done, and there it is on a silver plate. :smile: 

Now I only have to do read it one last time and tweak a few details. Then we'll be ready for launch!

**Comment by LoupVaillant** [comment]
I just noticed after installing my man pages that I cannot access our intro page.  When I type

    man 3monocypher intro

I get redirected to `intro(1)` instead. `man 3 intro` shows the general intro page for library functions.

Do you have the same issue?

**Comment by CuleX** [comment]
Cannot reproduce. Is the installation directory actually in your man path?

**Comment by LoupVaillant** [comment]
I think it is, (I use the default `/usr/local/share/man/man3`), and I can access the other man pages without any problem.

Must be a glitch on my machine.

**Comment by LoupVaillant** [comment]
I think it is, (I use the default `/usr/local/share/man/man3`), and I can access the other man pages without any problem.

Must be a glitch on my machine.

**Comment by LoupVaillant** [comment]
Found the problem! I have installed a version of `man` in `/usr/local/bin` by accident (presumably when I installed `mandoc` from source), and this minimal version screwed up some searches. It also used `more` as a pager, very annoying.

Now it works.

**Comment by CuleX** [comment]
Glad to see that's sorted out.

**Pull request merged**
